### ISSUE TITLE
NaN appears on all the dashboard reports

### ISSUE THREAD

**Issue by phuchoang2603** [cioraneanu/firefly-pico#89] opened 2024-07-18 10:57 UTC
Hi, I would like to understand how to resolve this issue. Presently, the app displays the total money I have, and all interactions with the app function quite well, except the small reports on the dashboard below do not show the correct numbers.

I'm wondering if this issue is related to my use of Firefly MariaDB instead of the recommended PostgreSQL in your setup guide. Additionally, I am using the Cloudflare tunnel for both the Firefly and Pico instances. 

Please let me know if you need any further information. Thank you very much.

![image](https://github.com/user-attachments/assets/8dee040f-6371-40ac-b5c8-200ce5945280)

**Comment by cioraneanu** [comment] 2024-07-18 12:05
Hi, the database and cloudflare tunnels should not be a factor.

To debug it you could try cloning the repository locally and starting up the frontend only. Then inside the UI -> App settings -> Pico Backend URL set it to your actual docker installation just like the production app. [Info](https://github.com/cioraneanu/firefly-pico/blob/main/docs/contribute.md#frontend-development)

A good place to start investigating would be the [Total income](https://github.com/cioraneanu/firefly-pico/blob/main/front/stores/dataStore.js#L172)

**Comment by avee87** [comment] 2024-07-18 16:49
Do you use some non-standard currencies? I can imagine this issue happening if you use currency conversion on the dashboard but there are no conversion rates for your currency.

**Comment by phuchoang2603** [comment] 2024-07-19 16:09
> Do you use some non-standard currencies? I can imagine this issue happening if you use currency conversion on the dashboard but there are no conversion rates for your currency.

I’m curious if the Vietnamese Dong (VND) is considered a non-standard currency. From what I can see, there are conversion rates between USD and VND available on the extras tab.

![IMG_0623](https://github.com/user-attachments/assets/7ae0c35c-e74d-47dd-8cbf-9e2b1464fdf2)

**Comment by phuchoang2603** [comment] 2024-07-19 16:11
> Hi, the database and cloudflare tunnels should not be a factor.
> 
> To debug it you could try cloning the repository locally and starting up the frontend only. Then inside the UI -> App settings -> Pico Backend URL set it to your actual docker installation just like the production app. [Info](https://github.com/cioraneanu/firefly-pico/blob/main/docs/contribute.md#frontend-development)
> 
> A good place to start investigating would be the [Total income](https://github.com/cioraneanu/firefly-pico/blob/main/front/stores/dataStore.js#L172)

Yes, I’ve cloned it and I’m still waiting for the npm install to finish. I’m not sure why it’s taking so long—my computer has been stuck for about 2 hours now.

**Comment by cioraneanu** [comment] 2024-09-11 16:39
Closing as cant reproduce

**Closed** 2024-09-11 16:39 UTC

**Comment by kelvinchin12070811** [comment] 2024-11-13 17:08
I have a similar issue on MYR, but however have solved it. **This is due to a configuration error on Firefly III** when creating the currency. The issue is when firefly-pico trying to convert the currency to another (at most case will convert back to the same currency), this configuration error will cause the convertion fall in to NaN as it cannot find the proper exchange rate which returns undefined, eg the following screenshot of the debugger.

![image](https://github.com/user-attachments/assets/b16c3110-f32a-417d-9c10-e3462a5941db)

The solution is if the desire country's currency did not by default listed in firefly III, make sure to create it properly, or update it and delete all the site data (including session storage & local storage) and refresh it should work. Eg following is for MYR:

![image](https://github.com/user-attachments/assets/cf518d30-8d39-4306-8181-dc220c728b4c)
