### ISSUE TITLE
ARM build

### ISSUE THREAD

**Issue by nghduc97** [cioraneanu/firefly-pico#34] opened 2024-05-11 16:05 UTC
Currently, the image cannot be built on ARM server because the [base Docker image](https://hub.docker.com/r/stsdockerhub/php) doesn't have an ARM version. Can a more popular Laravel base image be used to solve this?

To support ARM involves 2 tasks:
- Change Docker build to support ARM architecture.
- Update Github Actions to build for multiple platforms.

**Comment by cioraneanu** [comment] 2024-05-11 17:01
Duplicate of #10. Please keep the discussion in a single place.

**Closed by cioraneanu** 2024-05-11 17:01 UTC
